### ISSUE TITLE
1.4.2 Modificar medicamentos

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#12]
No regresa a página principal cuando nos encontramos en modificar medicamentos, al hacer click en el botón inicio

![modificar medicamentos_inicio](https://user-images.githubusercontent.com/39772031/57505256-3aa83b80-72bd-11e9-9119-e8620825f655.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57545282-77a51a00-731f-11e9-8000-3af573079e9c.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57545298-8095eb80-731f-11e9-9d44-792ec85403a3.png)
