### ISSUE TITLE
Título de modificar medicamentos

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#15]
Habrá que modificar y poner "modificar medicamentos", este deberá ser de tamaño 20, en lugar de tener un tamaño de 28 y tener "modificar datos del medicamento" 
![modificar medimaneotos](https://user-images.githubusercontent.com/39772031/57505653-d4bcb380-72be-11e9-9bb7-853c4c54fad9.jpeg)

Se anexa como debría ser
![modificar medicmentos_pantalla](https://user-images.githubusercontent.com/39772031/57505666-e30acf80-72be-11e9-92fb-e47abd126458.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57545163-24cb6280-731f-11e9-9172-477ca43e95e5.png)
