### ISSUE TITLE
Dar formato a modificar datos del medicamento

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#16]
Hay que tratar de ajustar los botones que se encuentran en el lado izquierdo, para que no se vean tan espaciados, así como ponerlos en el orden que les corresponde.

![modificar medimaneotos](https://user-images.githubusercontent.com/39772031/57506084-5bbe5b80-72c0-11e9-941c-3c7c43f6c241.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57547929-4d565b00-7325-11e9-9c83-2dae18e20255.png)
Favor de agregar mas información para replicar el error ya que no se mostró.
