### ISSUE TITLE
Descripción-  Módulo 1.4 Inventario  de medicamentos

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#17]
En el módulo 1.4 Inventario  de medicamentos- En la columna de Descripción no aparece en la tabla.
o	Descripción se refiere a aquella que se le da dependiendo de cómo se presente el medicamento, si son capsulas, tabletas o si el medicamento es soluble. (tipo varchar).

![5](https://user-images.githubusercontent.com/48162509/57506292-03d42480-72c1-11e9-84ad-ad30f2b24f69.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57874480-4a9caf80-77d6-11e9-8761-6df822d10fa3.png)
