### ISSUE TITLE
Búsquedas por Nombre- Modulo 1.4 Inventario de medicamento

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#18]
En el código de barras , permitir las búsquedas por Nombre( Si desplegar opciones con la primera letra) 

Si realiza las búsquedas por Nombre pero no despliega las opciones con la primera letra.

![6](https://user-images.githubusercontent.com/48162509/57506802-89a49f80-72c2-11e9-8187-08f6766eb2dd.jpeg)

![7](https://user-images.githubusercontent.com/48162509/57506816-92957100-72c2-11e9-8b95-7b6b9d04f16c.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57547983-7d056300-7325-11e9-993a-a0d6567ca994.png)
