### ISSUE TITLE
Usuario

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#2]
En la pantalla login, aún no se encuentra activo el usuario, se acceso con sólo dar click en "aceptar"
![login](https://user-images.githubusercontent.com/39772031/57501694-1c870f00-72ae-11e9-97e9-d6b8171e0829.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58060777-9d5ccb00-7b38-11e9-8b12-c2a1d65292a3.png)
