### ISSUE TITLE
Alerta para eliminar producto- Módulo 1.4 Inventario de medicamentos

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#20]
En el módulo 1.4 Inventario de medicamentos:

En la tabla de productos  al eliminar un producto, agregar mensaje   donde mande una alerta Preguntando si en verdad se quiere eliminar el producto. ¿SEGURO QUIERES ELIMINAR ESTE PRODUCTO?

![8](https://user-images.githubusercontent.com/48162509/57508203-7dbadc80-72c6-11e9-868c-40df2d655adf.jpeg)

**Comment by IvaNanis** [comment]
<script type="text/javascript">
       function confirmDelete() {
           var confirmar = confirm("¿Realmente desea eliminarlo? ");
           if (confirmar) {
               return true;
           } else {
               return false;
           }
       }
   </script>

/*EL SIGUIENTE CÓDIGO SE AGREGA AL BOTÓN DE ELIMINAR*/
onclick="return confirmDelete();"

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57549315-d4590280-7328-11e9-843e-5cc30293ba00.png)
