### ISSUE TITLE
Error en el módulo 1.5.1 Insertar médicos. El orden de los botones  GUARDAR y REGRESAR

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#21]
Solo cambiar el orden de los botones, según el formato de requerimientos deben estar así: INICIO, REGRESAR, GUARDAR.    y  están: INICIO, GUARDAR Y REGRESA

![2](https://user-images.githubusercontent.com/48162509/57894170-6cfcf000-780b-11e9-8daa-be4d0bb3c12d.jpeg)

![5](https://user-images.githubusercontent.com/48162509/57894249-cb29d300-780b-11e9-849a-13cafb5df35d.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061166-a77fc900-7b3a-11e9-9061-5ae05f7af141.png)
