### ISSUE TITLE
Error en el módulo 1.5.1  Insertar médicos : el botón GUARDAR no funciona.

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#22]
El botón GUARDAR: este botón servirá para guardar los datos del médico que hayamos ingresado correctamente.

* No guarda, marca error.

![4](https://user-images.githubusercontent.com/48162509/57894623-21e3dc80-780d-11e9-9a76-44b785b43b9f.jpeg)

![3](https://user-images.githubusercontent.com/48162509/57894747-a9c9e680-780d-11e9-9281-d507c1935d96.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061193-c8e0b500-7b3a-11e9-82cf-951e40210416.png)
