### ISSUE TITLE
Error en el módulo 1.5.1  Insertar médicos : No dice  NUEVO EMPLEADO, está como NUEVO MEDICO

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#23]
Se colocará la palabra NUEVO EMPLEADO, con un tipo de letra Arial, tamaño 20 y un color Powderblue (#B0E0E6). 

No dice  NUEVO EMPLEADO, está como NUEVO MEDICO según el formato de requerimientos.

![1](https://user-images.githubusercontent.com/48162509/57895014-07126780-780f-11e9-853a-f90b7058e83f.jpeg)

![6](https://user-images.githubusercontent.com/48162509/57895131-b8190200-780f-11e9-9ae4-3998aa93ab26.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061278-10ffd780-7b3b-11e9-8c28-467d11070292.png)
