### ISSUE TITLE
Error en el módulo 1.5.1  Insertar médicos : las cajas   de texto  no tienen letras tenues

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#24]
las cajas de texto  tendrán que tener la siguiente forma en cuanto a las letras tenues que aparecen, en cuanto el capturista de click en alguna de las cajas, las letras tendrán que desaparecer para poder escribir lo que ahí se pide.

*Las cajas de  texto no  tienen las letras tenues, como lo especifica el formato de requerimientos.

![7](https://user-images.githubusercontent.com/48162509/57895635-41c9cf00-7812-11e9-9fcf-745b5239faa8.jpeg)

![8](https://user-images.githubusercontent.com/48162509/57895637-45f5ec80-7812-11e9-9297-4d66e092660f.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061422-aef3a200-7b3b-11e9-89cd-a28ef78b9ca6.png)
