### ISSUE TITLE
MODICAR MEDICAMENTO, A VECES NO APARECE ICONOS

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#25]
A VECES NO APARECE ICONOS CON EL FIREFOX
![MODIFICAR MEDICAMENTO CHROME](https://user-images.githubusercontent.com/39772031/57896437-6031c980-7816-11e9-8d97-7d12295e479c.jpeg)
![MODIFICAR MEDICAMENTO FIREFOX](https://user-images.githubusercontent.com/39772031/57896438-6031c980-7816-11e9-801b-efe5a601e6a3.jpeg)

**Comment by danielhernandezm** [comment]
![Uploading image.png…]()
