### ISSUE TITLE
FORMATO DE CONTROL DE MÉDICOS

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#26]
DIFERENTE FORMATO QUE DE DISEÑO.

- NO CONTIENE LA LUPA, ADEMÁS QUE TIENE LÁPIZ Y CRUZ

- APARTADO HABRÁ UNA ACCIÓN DE MODIFICAR Y VER (SU COLOR SERÁ ROJO Y LA PALABRA TENDRÁ QUE IR SUBRAYADA) EL CUAL PERMITIRÁ MODIFICAR LOS DATOS DE LA TABLA, AL DARLE CLICK, NOS LLEVARA A UNA NUEVA PANTALLA DONDE SE MODIFICARA Y SE VERÁ DICHO MÉDICO.

![imagen](https://user-images.githubusercontent.com/39772031/57896545-de8e6b80-7816-11e9-97c8-c248eb7b828a.png)
![imagen](https://user-images.githubusercontent.com/39772031/57896553-e51ce300-7816-11e9-89b1-9c0cb380dd4e.png)

**Comment by danielhernandezm** [comment]
N/A
