### ISSUE TITLE
TAMAÑO DE LETRA  EN CONTROL DE MÉDICOS

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#27]
EL TAMAÑO DEBERÁ SER DE 14 Y ESTÁ DE 16

![imagen](https://user-images.githubusercontent.com/39772031/57896818-3a0d2900-7818-11e9-8af7-687add54244e.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061523-1ad60a80-7b3c-11e9-949c-18d8515b684e.png)
