### ISSUE TITLE
Error en el módulo 1.5.1  Insertar médicos : Alineación y espaciado de cajas de texto, iconos .

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#28]
Alineaciòn, formato  y espaciado de cajas de texto, iconos  no están conforme al formato de requerimientos. Como se muestra en la imagen.

![9](https://user-images.githubusercontent.com/48162509/57896939-c881aa80-7818-11e9-9bec-20b23be3e377.jpeg)

![10](https://user-images.githubusercontent.com/48162509/57896944-cfa8b880-7818-11e9-82f8-35fc4f75066e.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58342134-83abd400-7e15-11e9-9547-4384f55f5de5.png)
