### ISSUE TITLE
CAMBIAR DE MODIFICAR MEDICO A MODIFICAR EMPLEADO

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#29]
CAMBIAR EL NOMBRE A MODIFICAR EMPLEADO Y ALINEAR LOS ICONOS IZQUIERDOS 

![imagen](https://user-images.githubusercontent.com/39772031/57897307-c2d89480-7819-11e9-8bfa-a2fcda84538e.png)
![imagen](https://user-images.githubusercontent.com/39772031/57897317-d126b080-7819-11e9-8e8d-7069f9dcc153.png)

**Comment by danielhernandezm** [comment]
N/A
