### ISSUE TITLE
Validar usuario

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#3]
En el 1.1 "pantalla login", no valida, no manda alerta cuando los valores se encuentren vacíos.

**Las cajas de texto al recibir los valores deberán validar que sea un usuario válido, así como que estás no estén vacías mostrando un mensaje de:
o        Usuario no válido.
o        Debes ingresar usuario y contraseña**

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58060956-88cd0280-7b39-11e9-95bf-55d5a0ce1b8c.png)
