### ISSUE TITLE
No aparece texto en las cajas

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#30]
En las cajas de texto serán de 14. Y las letras serán tipo Arial.

Anteriormente sí aparecían 

![imagen](https://user-images.githubusercontent.com/39772031/57897485-89ecef80-781a-11e9-9e99-813e2069e3f5.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061543-32ad8e80-7b3c-11e9-9a0f-9c55eb16bce4.png)
