### ISSUE TITLE
Alineación de iconos

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#31]
Los iconos se encuentran tamaño diferente entre ellos.

- inicio, regresar y guardar

![imagen](https://user-images.githubusercontent.com/39772031/57897572-0f709f80-781b-11e9-9a20-f0f3c1f8de3a.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58342095-68d95f80-7e15-11e9-8e7d-fdd617b4cddb.png)
