### ISSUE TITLE
No permite agregar medicamento

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#32]
Error al agregar medicamento
![imagen](https://user-images.githubusercontent.com/39772031/57897710-c1a86700-781b-11e9-9be5-c95c1c7efe70.png)

![imagen](https://user-images.githubusercontent.com/39772031/57897786-0d5b1080-781c-11e9-8017-5c74115ea411.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58061556-448f3180-7b3c-11e9-9905-1da6ad1d7292.png)
