### ISSUE TITLE
Iconos fuera de su posición

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#33]
Los iconos se encuentran fuera.
![imagen](https://user-images.githubusercontent.com/39772031/57897922-89edef00-781c-11e9-8ff5-d0d990e86ffe.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58342166-9cb48500-7e15-11e9-9f33-28dc9852f9c7.png)
