### ISSUE TITLE
Error en el modulo de medicos

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#34]
En el apartado de agregar, desaparece el botón de GUARDAR en el navegador firefox

![error boton desaparece](https://user-images.githubusercontent.com/48162509/58373026-5ed66000-7eec-11e9-85ff-a9b50055bac7.png)

**Comment by danielhernandezm** [comment]
Usar solo google chrome para la ejecución del sistema.

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58662430-cc6cfc80-82ef-11e9-8fd9-5493fa52251e.png)
