### ISSUE TITLE
Modificación en el modulo MÉDICOS 

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#35]
El botón de actualizar (refresh) es muy pequeño, debe ser mas grande.

![modificacion boton refresh](https://user-images.githubusercontent.com/48162509/58373022-5120da80-7eec-11e9-89a5-440abd8ae4c1.png)

**Comment by danielhernandezm** [comment]
No es botón actualizar, la función del botón es ir atrás.
![Uploading image.png…]()
