### ISSUE TITLE
Modificación del modulo Médicos y Medicamentos

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#37]
Agregar botón regresar en ambos módulos después de realizar una búsqueda.

![regresar medicos](https://user-images.githubusercontent.com/48162509/58373015-2767b380-7eec-11e9-98e1-744e4abb2651.png)

![regresar medicamentos](https://user-images.githubusercontent.com/48162509/58373017-3189b200-7eec-11e9-93eb-378dddbe5848.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/58496541-b7ea0200-813f-11e9-9b04-c8d1bfdc4747.png)
Este issue no aplica, el boton regresar ya hace esa funcion, favor de revisar bien el sistema.
