### ISSUE TITLE
Botón guardar

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#4]
El botón deberá ir con nombre guardar en lugar de agregar
![Botón guardar](https://user-images.githubusercontent.com/39772031/57502158-18f48780-72b0-11e9-816c-aeec50868a16.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57544230-5db60800-731c-11e9-9d1d-0de337889b6f.png)
