### ISSUE TITLE
Error en el modulo 1.3 Página principal -Desajuste en el menù

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#5]
Arreglar desajuste  de imagen, iconos, espacio entre los botones deben estar alineados, es decir en cada uno de los botones se insertará la imagen a lado izquierdo de acuerdo a su referencia.

![1](https://user-images.githubusercontent.com/48162509/57502149-037f5d80-72b0-11e9-9e54-c383eaea4150.jpeg)

![Captura de pantalla (21)](https://user-images.githubusercontent.com/48162509/57502272-9a4c1a00-72b0-11e9-9a30-d9c1a8c466f3.png)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57544299-92c25a80-731c-11e9-8552-91596012bae4.png)


Favor de agregar mas información para poder replicar el error.
