### ISSUE TITLE
Tamaño de letra de nuevo medicamento

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#6]
En 1.4.1 agregar medicamento, el tamaño de la letra **"Nuevo medicamento"** aparece con un tamaño de letra 28 cuando deberá ser de un tamaño 20
![nuevo medicamento](https://user-images.githubusercontent.com/39772031/57502353-00d13800-72b1-11e9-9f2b-d6e4fe2a714e.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57544495-1bd99180-731d-11e9-864b-f4381c79f025.png)
