### ISSUE TITLE
Diseño del apartado 1.4.1 agregar medicamentos

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#7]
Título de inventario de medicamentos más pequeño que en propuesta de diseño, no cumple con el diseño.

Se adjunta una imagen de como deberá ser el diseño
![imagen](https://user-images.githubusercontent.com/39772031/57503276-0a5c9f00-72b5-11e9-97b5-494c865061e7.png)

Y así es como se presenta
![pantalla nuevo medicamento](https://user-images.githubusercontent.com/39772031/57503454-c9b15580-72b5-11e9-9725-f28e9fe99bb3.jpeg)

Es importante mencionar que está se mueve, por lo que es importante realizar el ajuste necesario
![nuevo medicamento_movido título](https://user-images.githubusercontent.com/39772031/57503468-df267f80-72b5-11e9-9770-fe58d7d19ace.jpeg)

Los iconos del lado izquierdo están en diferente orden
![iconos de nuevo medicamento](https://user-images.githubusercontent.com/39772031/57503529-16952c00-72b6-11e9-99d7-d0181e6ab40a.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57544719-dc5f7500-731d-11e9-9689-54fc75650aed.png)
Favor de agregar mas información para replicar error "se mueve"
