### ISSUE TITLE
Error en el módulo 1.3 Página principal - No permitir modificación de enlace de login

### ISSUE THREAD

**Issue by alejandra-Mk** [amolitos/fine4you#8]
Error en el módulo 1.3 Página principal - No permitir modificación de enlace de login.
No permitir  entrar  al modulo de la página principal  y demás módulos, modificando el enlace de login como se ve en la imagen.
Estando en el login  se puede modificar el enlace para entrar a otro módulo , él cual de nada serviría el login para hacer valido el acceso a la información de la empresa. 

![2](https://user-images.githubusercontent.com/48162509/57503492-f06f8c00-72b5-11e9-9967-a4b43d17c592.jpeg)

**Comment by danielhernandezm** [comment]
![Uploading image.png…]()
