### ISSUE TITLE
1.4 Inventario de medicamentos

### ISSUE THREAD

**Issue by anniiian** [amolitos/fine4you#9]
En el botón agregar e inicio, se encuentra en otro lado
![inventario de medicamentos](https://user-images.githubusercontent.com/39772031/57503887-d6cf4400-72b7-11e9-8c79-0a9db2c0dafe.jpeg)

Adjunto en el lugar correcto de deberá ir
![pantalla inventario de medicamentos](https://user-images.githubusercontent.com/39772031/57503902-e5b5f680-72b7-11e9-83f4-d3702b19dbf6.jpeg)

**Comment by danielhernandezm** [comment]
![image](https://user-images.githubusercontent.com/48160735/57874764-f7772c80-77d6-11e9-94b8-0a9b0f4be322.png)
